[package]
name = "champr"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lcu = { path = "../lcu" }
tokio = { version = "1.44.0", features = ["full"] }
slint = { version = "1.15", features = ["renderer-software"] }
kv-log-macro = "1.0.7"
femme = "2.2.1"
anyhow = "1.0.86"
image = { version = "0.25.2", default-features = false, features = ["png"] }
futures-util = "0.3.31"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5"
tray-icon = "0.19"
windows-sys = { version = "0.52", features = [
    "Win32_Graphics_Gdi",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
slint-build = "1.15"
embed-resource = "2.5"
